### ISSUE TITLE
There appears to be a bug installing lisp-unit2

### ISSUE THREAD

**Issue by joshmarlow** [AccelerationNet/lisp-unit2#5]
I've tried installing via quicklisp with this command: `(ql:quickload :lisp-unit2)`

I receive the following error message:

```
; Loading "lisp-unit2"
..................................................
[package cl-interpol].............................
[package lisp-unit2]..............................
[package lisp-unit2-asserts]......................
.
debugger invoked on a SB-KERNEL:SIMPLE-PACKAGE-ERROR in thread
#<THREAD "initial thread" RUNNING {1002998EB3}>:
  The name "ASDF/SYSTEM" does not designate any package.

Type HELP for debugger help, or (SB-EXT:QUIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [RETRY ] Retry compiling #<CL-SOURCE-FILE "lisp-unit2" "interop">.
  1: [ACCEPT] Continue, treating
              compiling #<CL-SOURCE-FILE "lisp-unit2" "interop"> as having been
              successful.
  2: [ABORT ] Give up on "lisp-unit2"
  3:          Exit debugger, returning to top level.

(SB-INT:%FIND-PACKAGE-OR-LOSE "ASDF/SYSTEM")
```

I've also attempted to install via ASDF with this command `(asdf:load-system :lisp-unit2)`

And received this error message:

```
; compiling (IN-PACKAGE :LISP-UNIT2)
; compiling (DEFGENERIC CONVERT-TEST-RESULTS ...)
; compiling (DEFGENERIC CONVERT-TEST-RESULT ...);
; caught ERROR:
;   READ error during COMPILE-FILE:
;
;     Package ASDF/SYSTEM does not exist.
;
;       Line: 17, Column: 49, File-Position: 565
;
;       Stream: #<SB-SYS:FD-STREAM
;                 for "file /Users/joshmarlow/Devel/josh-general-backup/common-lisp/libs/lisp-unit2/interop.lisp"
;                 {1340A799}>

; compilation aborted after 0:00:00.044

debugger invoked on a ASDF:COMPILE-ERROR:
  Error while invoking #<COMPILE-OP NIL {13FA07F9}> on
  #<CL-SOURCE-FILE "lisp-unit2" "interop">

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [RETRY ] Retry compiling #<CL-SOURCE-FILE "lisp-unit2" "interop">.
  1: [ACCEPT] Continue, treating
              compiling #<CL-SOURCE-FILE "lisp-unit2" "interop"> as having been
              successful.
  2: [ABORT ] Exit debugger, returning to top level.

((:METHOD ASDF:PERFORM (ASDF:COMPILE-OP ASDF:CL-SOURCE-FILE)) #<ASDF:COMPILE-OP NIL {13FA07F9}> #<ASDF:CL-SOURCE-FILE "lisp-unit2" "interop">) [fast-method]
0] ;
; compilation unit aborted
;   caught 2 fatal ERROR conditions
;   caught 1 ERROR condition
*
```

Let me know if/how I can assist in debugging/reproducing this.  I'm quite new to Common Lisp, but am happy to help :)

**Comment by bobbysmith007** [comment]
It sounds like you have a newer / older version of sbcl / asdf than my library expects. The easiest debug would be to delete the `/system` in asdf/system on line 17 of that file and auto complete. That will tell you what symbol it expects and we can write a patch to accommodate.

**Comment by bobbysmith007** [comment]
Not near a computer right now but I can look into this Monday

**Comment by joshmarlow** [comment]
Thanks for the quick response.  Feel free to put this on the back-burner until Monday.

OSX versions:
SBCL version: SBCL 1.1.6.0-3c5581a
ASDF version installed in ~/quicklisp: ASDF 2.26

I also did a clean install of sbcl and quicklisp on a Linux box on Vagrant and received the same error.

Ubuntu versions:
SBLC version: SBCL 1.0.55.0.debian
ASDF version installed in ~/quicklisp: ASDF 2.26

On OSX, I removed the `/system` part as you suggested and now receive a new error on the following line saying that  `ASDF/COMPONENT` does not exist.  Removing the `/component` portion then leads to a complaint about `SIDEWAY-DEPENDENCIES` not being in the ASDF package.

Thanks for the help and have a good weekend!

**Comment by bobbysmith007** [comment]
Wow, sorry that I missed this forever.  At least I found a screen in github that finally showed me it was still here.  I have continued to use access succesfully on default sbcl/quicklisp/asdf installs

For me this is currently:  asdf "3.1.3", sbcl: 1.2.14, ql: 2015-01-28.  

If you are installing SBCL via your package manager, you are probably better off compiling from source (which for me has been mostly painless, especially with sbcl already installed once).  The versions you list are a few years old, and a lot has changed since then.  While I would like it to work out whats wrong and provide alternative interop, its a bit difficult to install asdf at this point (I think)

**Comment by thoto** [comment]
I'm still using asdf 2.26 and should consider upgrading it but I think I got a solution to this problem.

_This may be wrong_ but it compiled after replacing `asdf/component:sideway-dependencies` by `:load-dependencies`. I do not know what is stored in this slot and do not want to look deeper inside the documentation, but the names seem right to me. And it works at least for me.

**Comment by bobbysmith007** [comment]
Thanks for your insight into this.  Adding a patch now

**Comment by bobbysmith007** [comment]
I tried 3b52b8c886428947f0b02af859b7eccf34966201 but I dont know how to easily test against an older verion of asdf.  Please reopen if it still doesnt work
